

#OCTAVES
#2 to 7
MIN_OCTAVE = 2
MAX_OCTAVE = 7
OCTAVES = range(MIN_OCTAVE, MAX_OCTAVE + 1)
NUM_OCTAVES = len(OCTAVES)
OCTAVE_IDX = range(NUM_OCTAVES)


#NOTES
DIATONIC = list('cdefgab')
REST = ['r']
DIATONIC_REST = DIATONIC + REST
NUM_DIATONIC_REST = len(DIATONIC_REST)
NOTE_IDX = range(NUM_DIATONIC_REST)
NUM_NOTES  = NUM_OCTAVES * NUM_DIATONIC_REST

# ABS_RESTS = [ 
# print 'Num notes, num diatonic rest, num octaves'
# print NUM_NOTES, len(DIATONIC_REST), len(OCTAVES)

DEFAULT_DURATION = 4
BARS_PER_SECTION = 8
BEATS_PER_BAR = 4
BEATS_PER_SECTION = BARS_PER_SECTION * BEATS_PER_BAR


TONIC = 'c'
CHORD_NOTES = 'ceg'
